# Generated by Django 6.0.1 on 2026-01-30 05:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_division'),
    ]

    operations = [
        migrations.AddField(
            model_name='employeeprofile',
            name='division',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='employees', to='users.division'),
        ),
    ]
