# Generated by Django 6.0.1 on 2026-01-30 19:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_fcmtoken'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employeeprofile',
            name='division',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='employees', to='users.division'),
        ),
    ]
