# Generated by Django 6.0.1 on 2026-01-30 04:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='office',
            name='work_end_time',
            field=models.TimeField(default='18:00'),
        ),
        migrations.AddField(
            model_name='office',
            name='work_start_time',
            field=models.TimeField(default='09:30'),
        ),
    ]
