# Generated by Django 6.0.1 on 2026-01-30 05:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0002_office_work_end_time_office_work_start_time'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='locationlog',
            options={},
        ),
        migrations.RemoveField(
            model_name='locationlog',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='locationlog',
            name='millis',
        ),
        migrations.AlterField(
            model_name='locationlog',
            name='recorded_at',
            field=models.DateTimeField(db_index=True),
        ),
        migrations.AlterField(
            model_name='locationlog',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
