# Generated by Django 6.0.1 on 2026-01-30 06:01

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0003_alter_locationlog_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='locationlog',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='locationlog',
            name='recorded_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
