# Generated by Django 6.0.1 on 2026-01-30 06:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0004_locationlog_created_at_alter_locationlog_recorded_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='locationlog',
            name='millis',
            field=models.BigIntegerField(blank=True, null=True),
        ),
    ]
