# Generated by Django 6.0.1 on 2026-01-30 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0006_geofenceevent'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendance',
            name='was_inside',
            field=models.BooleanField(default=False),
        ),
    ]
