# Generated by Django 6.0.1 on 2026-01-31 09:57

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0007_attendance_was_inside'),
    ]

    operations = [
        migrations.AlterField(
            model_name='locationlog',
            name='recorded_at',
            field=models.DateTimeField(db_index=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
